### ISSUE TITLE
undetected_chromedriver issue

### ISSUE THREAD

**Issue by ysemenovkrop** [alexmudrak/solscan-parser#2]
Hi, have you happened to encounter this error? 

I have updated undetected-chromedriver with no success
_____________________________________________________________________________________________

INFO:     2024-05-02 20:47:49,727 - [services.google_sheets] - Initializing Google Sheets credentials.
INFO:     2024-05-02 20:47:49,728 - [services.google_sheets] - Loaded credentials from token file.
INFO:     2024-05-02 20:47:49,728 - [services.solscan_parser] - Entering to the browser...
INFO:uc:setting properties for headless
INFO:     2024-05-02 20:48:12,716 - [services.solscan_parser] - Try parse: 9sQFKCqFztZBvkBhDZdHKBBsfYsTrhiHWDjzdLFWhqWZ
INFO:     2024-05-02 20:48:41,846 - [services.solscan_parser] - Exiting from the browser...
ERROR:    2024-05-02 20:48:41,847 - [services.solscan_parser] - An exception occurred: Message: 
Stacktrace:
0   undetected_chromedriver             0x0000000101365a18 undetected_chromedriver + 5216792
1   undetected_chromedriver             0x000000010135d653 undetected_chromedriver + 5183059
2   undetected_chromedriver             0x0000000100ecf527 undetected_chromedriver + 406823
3   undetected_chromedriver             0x0000000100f1aff2 undetected_chromedriver + 716786
4   undetected_chromedriver             0x0000000100f1b181 undetected_chromedriver + 717185
5   undetected_chromedriver             0x0000000100f5f1d4 undetected_chromedriver + 995796
6   undetected_chromedriver             0x0000000100f3d72d undetected_chromedriver + 857901
7   undetected_chromedriver             0x0000000100f5c6bf undetected_chromedriver + 984767
8   undetected_chromedriver             0x0000000100f3d4a3 undetected_chromedriver + 857251
9   undetected_chromedriver             0x0000000100f0dfe3 undetected_chromedriver + 663523
10  undetected_chromedriver             0x0000000100f0e92e undetected_chromedriver + 665902
11  undetected_chromedriver             0x0000000101323930 undetected_chromedriver + 4946224
12  undetected_chromedriver             0x00000001013299e4 undetected_chromedriver + 4970980
13  undetected_chromedriver             0x000000010130442e undetected_chromedriver + 4817966
14  undetected_chromedriver             0x000000010132a4f9 undetected_chromedriver + 4973817
15  undetected_chromedriver             0x00000001012f46b4 undetected_chromedriver + 4753076
16  undetected_chromedriver             0x000000010134cba8 undetected_chromedriver + 5114792
17  undetected_chromedriver             0x000000010134cd67 undetected_chromedriver + 5115239
18  undetected_chromedriver             0x000000010135d273 undetected_chromedriver + 5182067
19  libsystem_pthread.dylib             0x00007ff81201018b _pthread_start + 99
20  libsystem_pthread.dylib             0x00007ff81200bae3 thread_start + 15

Traceback (most recent call last):
  File "/Users/Documents/GitHub/solscan-parser/src/main.py", line 32, in <module>
    parser.process_hashes()
  File "/Users/Documents/GitHub/solscan-parser/src/services/solscan_parser.py", line 141, in process_hashes
    parse_result = self.get_parse_result(hash)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Documents/GitHub/solscan-parser/src/services/solscan_parser.py", line 134, in get_parse_result
    result = self.parse_sol_values(result, driver)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Documents/GitHub/solscan-parser/src/services/solscan_parser.py", line 76, in parse_sol_values
    sol_balance_element = WebDriverWait(driver, 20).until(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Library/Caches/pypoetry/virtualenvs/solscan-parser-RvbEvgF2-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)

**Comment by alexmudrak** [comment]
Hey, @ysemenovkrop, thanks for your issue.
Please try using the latest version. (https://github.com/alexmudrak/solscan-parser/pull/3)
